name: reviewdog-suggest
on: [pull_request]
jobs:
  kotlin:
    name: runner / suggester / spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew spotlessKotlinApply
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless