name: reviewdog-suggest

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  reviewdog-suggest:
    name: runner / suggester / spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run SpotlessKotlinApply
        run: ./gradlew spotlessKotlinApply

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless